doctrine:
    dbal:
        connections:
            default:
                # Default database connection configuration
                url: '%env(resolve:DATABASE_URL)%'
            ffxiv:
                # FFXIV-related database connection configuration
                url: '%env(resolve:FFXIV_DATABASE_URL)%'
            anime: 
                # Anime database connection configuration
                url: '%env(resolve:ANIME_DATABASE_URL)%'
            leagueoflegends:
                # League Of Legends database connection configuration
                url: '%env(resolve:LEAGUEOFLEGENDS_DATABASE_URL)%'
        default_connection: default
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Base:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Base'
                        prefix: 'App\Entity\Base'
                        alias: Base
            ffxiv:
                connection: ffxiv
                mappings:
                    FFXIV:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/FFXIV'
                        prefix: 'App\Entity\FFXIV'
                        alias: FFXIV
            anime:
                connection: anime
                mappings:
                    Anime:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Anime'
                        prefix: 'App\Entity\Anime'
                        alias: Anime
            leagueoflegends:
                connection: leagueoflegends
                mappings:
                    LeagueOfLegends:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/LeagueOfLegends'
                        prefix: 'App\Entity\LeagueOfLegends'
                        alias: LeagueOfLegends

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
