base_controller:
    resource:
        path: ../src/Controller/Base
        namespace: App\Controller\Base
    type: attribute

ffxiv_controller:
    resource:
        path: ../src/Controller/FFXIV
        namespace: App\Controller\FFXIV
    type: attribute

anime_controller:
    resource: 
        path: ../src/Controller/Anime
        namespace: App\Controller\Anime
    type: attribute

leagueoflegends_controller:
    resource:
        path: ../src/Controller/LeagueOfLegends
        namespace: App\Controller\LeagueOfLegends
    type: attribute
