base_controller:
    resource:
        path: ../src/Controller/Base
        namespace: App\Controller\Base
    type: attribute

ffxiv_controller:
    resource:
        path: ../src/Controller/FFXIV
        namespace: App\Controller\FFXIV
    type: attribute

